[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
#transfer_hook = "<transfer hook address returned by 'yarn anchor keys list'>"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
